services:
  bifrost:
    image: maximhq/bifrost:v1.4.18
    container_name: bifrost
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/data/config.json
    networks:
      - pgvector_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  pgvector_network:
    external: true
